name: Build and Publish LLVM Build

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Release tag"
        required: true
        type: choice
        options:
          - core
      runner:
        description: "GitHub runner's OS"
        required: true
        type: choice
        options:
          - ubuntu-latest
          - windows-latest
          - macos-latest
jobs:
  edit-release:
    runs-on: ${{ github.event.inputs.os }}

    steps:
      - name: Display build info
        run: |
          echo "Runner OS: ${{ matrix.os }}"
          echo "Runner arch: $RUNNER_ARCH"

      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Validate tag exists
        run: |
          if ! git rev-parse "${{ github.event.inputs.tag }}" >/dev/null 2>&1; then
            echo "Tag [${{ github.event.inputs.tag }}] does not exist!"
            exit 1
          fi

      # - name: Update release notes (optional)
      #   if: ${{ github.event.inputs.notes != '' }}
      #   run: |
      #     gh release edit "${{ github.event.inputs.tag }}" \
      #       --notes "${{ github.event.inputs.notes }}"
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Upload asset to release
      #   run: |
      #     gh release upload "${{ github.event.inputs.tag }}" \
      #       "${{ github.event.inputs.file }}" \
      #       --clobber
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
